development: &default
  host: 'http://localhost:9200'
  transport_options:
  request:
  timeout: !!integer 300
test:
  <<: *default
staging:
  <<: *default
production:
  host: 'https://paas:f49902c6629cd3282b0d3b86c1610c65@oin-us-east-1.searchly.com'
  transport_options:
    request:
      timeout: !!integer 300
